version: '3'
services:
  fritzbox-logs:
    image: dkusidlo/fritzbox-logs:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - log-data:/data/fritzbox-logs-data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FBURL=http://fritz.box
      - FBUSER=user
      - FBPASS=password
      - FBINT=interval
      - FBAPPVOLUME=outputdir
    command: []

volumes:
  log-data:
